siteTopper/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='novaPiada'),
]

siteTopper/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('form/', views.formNovaQuestao, name='form'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

siteTopper/siteTopper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('blog/', include('blog.urls')),
]

siteTopper/blog/models.py
import uuid
from django.db import models
from django.utils import timezone

class Piada(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    titulo = models.CharField(max_length=200)

    conteudo = models.CharField(max_length=200)

    categoria = models.CharField(max_length=20)

    createdAt = models.DateTimeField(auto_now_add=True)

# class Usuario(models.Model):
#
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#
#     titulo = models.CharField(max_length=200)
#
#     data = start = models.DateTimeField( verbose_name='Data de Nascimento' )

siteTopper/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', null=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

siteTopper/blog/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Piada

def cadastro(request):
    if(request.method == 'POST'):
        inputs = request.POST
        p = Piada()
        p.titulo = inputs['titulo']
        p.conteudo = inputs['conteudo']
        p.categoria = inputs['categoria']
        p.save()
        return redirect('blog:index')
    context = ""
    template = 'cadastro_piada.html'
    return render(request, template, None)

def index(request):
    result = Piada.objects.all()
    for r in result:
        print(r.titulo)
    perdi = [{'titulo': "abacaxi"}, {'titulo': "teste"}, {'titulo': "carro"}, {'titulo': "super"}]
    context = {'piadas': perdi}
    template = 'index.html'
    return render(request, template, context)

siteTopper/polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .models import Choice, Question

def index(request):
    questoes = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': questoes}
    template = 'polls/index.html'
    return render(request, template, context)

def formNovaQuestao(request):
    if(request.method == 'POST'):
        aux = request.POST['nome_questao']
        teste = Question()
        teste.question_text = aux
        teste.save()
        return redirect('/')
    template = 'polls/novaQuestao.html'
    print("perdi")
    return render(request, template, None)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

siteTopper/blog/templates/cadastro_piada.html
<a href="{% url 'blog:index' %}">Voltar home</a>
<center>
    <h1>Cadastro Nova Piada</h1>
    <form method="POST">

        {% csrf_token %}

        <!-- TITULO PIADA -->
        <label for="titulo">Título piada</label>
        <input style="width:20%; margin-bottom:10px" type="text" name="titulo">
        <br>
        <!-- CONTEUDO -->
        <label for="conteudo">Conteúdo piada</label>
        <input style="width:20%; margin-bottom:10px" type="text" name="conteudo">
        <br>
        <!-- CATEGORIA -->
        <label for="categoria">Categoria</label>
        <select name="categoria">
            <option value="loira">Loira</option>
            <option value="gordo">Gordo</option>
            <option value="comunista">Comunista</option>
            <option value="anao">Anão</option>
        </select>
        <br>
        <!-- BTN SUBMIT -->
        <button type="submit" name="button" style="background-color: #008c9a; font-size: 16px; padding: 5px; width:15%; height: 30px; margin: 10px auto">
            Cadastrar
        </button>
    </form>
</center>

siteTopper/blog/templates/index.html
<h2>Blog de piadas</h2>

<h3>Lista de paidas</h3>

{% if piadas %}
    <ul>
    {% for p in piadas %}
        <li>
            <h4>
                {{ p.titulo }}
            </h4>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <h5>Sem piadas cadastradas</h5>
{% endif %}

<p>
    Cadastro piada <a href="{% url 'blog:novaPiada' %}">aqui</a>
</p>

<!-- <ul>
    <li>p1</li>
    <li>p2</li>
    <li>p3</li>
</ul> -->

siteTopper/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

siteTopper/polls/templates/polls/index.html
<h4>
    Nova questão, clique <a href="{% url 'polls:form' %}">aqui</a>
    Cadastro Piada <a href="{% url 'polls:form' %}">aqui</a>
</h4>
<br>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

siteTopper/polls/templates/polls/novaQuestao.html
<h1>Bla</h1>

<form method="post">
    {% csrf_token %}
    <label for=""></label>
    <input type="text" name="nome_questao" value="">

    <button type="submit" name="button">teste</button>

</form>

siteTopper/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>